import datetime

EXTERNAL_URL = 'http://localhost'
SERVER_URL = ''
BASE_DIR = ''
DATABASE_NAME = 'db.sqlite3'
SECRET_KEY = b'potato'
OUR_SENDER_EMAIL_ADDRESS = ''
LOGIN_SESSION_EXPIRATION_TIME = datetime.timedelta(weeks=4)

TELEGRAM_BOT_API_URL = ''
TELEGRAM_RELAY_BOT_API_TOKEN = ''
INTERNAL_TELEGRAM_BOT_API_TOKEN = ''
INTERNAL_TELEGRAM_BOT_ADMIN_CHAT_ID = '' # I'm the admin

AWS_ACCESS_KEY_ID = ''
AWS_SECRET_ACCESS_KEY = ''

S3_BUCKET = ''
S3_BUCKET_UNPROCESSED_INBOX_MAX_ITEMS_PER_RUN = 5
S3_BUCKET_PROCESSED_INBOX_KEY = ''
S3_BUCKET_UNPROCESSED_INBOX_KEY = ''

SES_REGION_NAME = 'us-east-1'

